name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: |
          go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: -v
          skip-cache: false

  test:
    runs-on: ubuntu-latest
    name: Go tests
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: |
        go get -t -d -v ./...
        go install github.com/bwplotka/bingo@v0.9.0
        bingo get -l

    - name: Run tests
      run: |
        ginkgo -r -cover --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress
        ginkgo -tags=gorillamux -r --randomizeSuites --failOnPending --trace --race
        ginkgo -tags=gingonic -r --randomizeSuites --failOnPending --trace --race
        ginkgo -tags=echo -r --randomizeSuites --failOnPending --trace --race
        rm examples/examples.coverprofile
        gover
        goveralls -coverprofile=gover.coverprofile -repotoken gY90SprlNRGmSMl7MgybLreYa05wUXJTU
